apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t2ial4r0j-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t2ial4r0j-nodejs 
  name: t2ial4r0j-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: t2ial4r0j-nodejs 
